### ISSUE TITLE
test_load fails on Windows with python=3.10

### ISSUE THREAD

**Issue by mdpiper** [csdms/bmi-topography#49]
The *test_load* test is failing on Windows, python=3.10, but only when [run through GitHub Actions](https://github.com/csdms/bmi-topography/actions/runs/2820888645). It passes when run locally. It also passes on Windows, python<3.10, when run through Actions. 

This may be an upstream problem with *xarray* or *rioxarray*. Here's the [stack trace](https://github.com/csdms/bmi-topography/runs/7735044715?check_suite_focus=true):
```
================================== FAILURES ===================================
__________________________________ test_load __________________________________
Traceback (most recent call last):
  File "C:\Miniconda\envs\topography\lib\site-packages\xarray\core\common.py", line 284, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: 'DataArray' object has no attribute '_file_obj'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\bmi-topography\bmi-topography\tests\test_topography.py", line 106, in test_load
    topo.load()
  File "D:\a\bmi-topography\bmi-topography\bmi_topography\topography.py", line 177, in load
    self._da = rioxarray.open_rasterio(_filename)
  File "C:\Miniconda\envs\topography\lib\site-packages\rioxarray\_io.py", line 775, in open_rasterio
    result._file_obj = manager
  File "C:\Miniconda\envs\topography\lib\site-packages\xarray\core\common.py", line 292, in __setattr__
    raise AttributeError(
AttributeError: cannot set attribute '_file_obj' on a 'DataArray' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.
```

**Comment by mdpiper** [comment]
Check if this behavior has changed the next time *bmi-topography* is updated.
